# Server configurations
app:
  env: "development"
  api_secret : "123456786"

server:
  host: "localhost"
  port: 8000

# Database credentials
database:
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: db
  DB_USERNAME: db
  DB_PASSWORD: db

redis:
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_DATABASE: 0
  REDIS_PASSWORD: