version: '3.1'

services:

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_ROOT_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80