version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - 3306:3306

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmingo
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80