version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
      - "redis"
    links:
      - "db"
      - "redis"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_ROOT_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"