version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
      - "redis"
    links:
      - "db"
      - "redis"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"