# Server configurations
app:
  env: "production"

server:
  host: "localhost"
  port: 8000

# Database credentials
database:
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: db
  DB_USERNAME: db
  DB_PASSWORD: db